### ISSUE TITLE
web demo issues , create dataset failed! 

### ISSUE THREAD

**Issue by wbbeyourself** [HKUSTDial/NL2SQL360#1]
![image](https://github.com/BugMaker-Boyan/NL2SQL360/assets/18190695/5122da0b-4382-47ea-bdc5-24dc57bb05b7)

**Comment by BugMaker-Boyan** [comment]
感谢您对我们工作的关注。

我们目前的Online Web Demo中，已经导入了名为"spider_dev"的数据集，您可以在右侧Dataset View的下拉列表中看到这一点，然而数据集的名称在当前demo中是unique的，所以会出现创建失败的提示。

另外，您也可以使用由"spider_example.py"或“bird_example.py”中创建的本地sqlite数据库([#Line6](https://github.com/BugMaker-Boyan/NL2SQL360/blob/d36befd9860c03c3a6624e0fafa3474c436a33ac/spider_example.py#L6)), 其中包含了所有数据，包括数据集特征，EX，EM以及VES评测分数等，使用本地撰写SQL进行查询对应的数据结果，如“查询Spider-Dev数据集中，DAILSQL方法在不同难度子集上的性能”:
`SELECT hardness, round(avg(exec_acc) * 100.0, 1) AS EX, round(avg(exact_acc) * 100.0) AS EM, round(avg(ves), 2) AS VES FROM DATASET_spider_dev_EVALUATION_DAILSQL AS e JOIN DATASET_spider_dev AS D ON e.id = d.id GROUP BY d.hardness;`

此外，我们将发布更加完备的Web System，感谢您的关注。
