### ISSUE TITLE
Reprod question

### ISSUE THREAD

**Issue by dil-ssoage** [HKUSTDial/NL2SQL360#11]
Sorry But i was wondering how to use this code to run the mentioned prompting strategies in the assets png. What i can see from the library it is mostly about dataset import, but I can not seem to find any model or prompting specific code. Sorry for the simple question but could you please advice on how to run a reprod run for prompting based strategies with like gpt4 or claude

**Comment by BugMaker-Boyan** [comment]
Sorry for the late reply, and thank you very much for your interest in our work!

This repository is currently focused on **maintaining the multi-perspective evaluation tool NL2SQL360 that we proposed**. The modules from the Design Space mentioned in our paper are based on **existing NL2SQL methods** (e.g., the Schema Linking module from RESDSQL). However, these repositories often lack a unified interface, which makes future maintenance challenging. Therefore, they have not been included in this repository.

_If you need it, I’d be happy to write a list of relevant methods along with links to their code and explanations._

**Comment by dil-ssoage** [comment]
That would extremely useful if you could! Thanks for the great work

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
