### ISSUE TITLE
前端页面咨询

### ISSUE THREAD

**Issue by ccckdi** [HKUSTDial/NL2SQL360#12]
请问这个项目对应的前端页面，目前是没有开源吗
![image](https://github.com/user-attachments/assets/9cce455a-4094-4ca9-a6d3-c309dab921ff)

**Comment by BugMaker-Boyan** [comment]
前端页面目前没有开源，当前可用两种方式来使用NL2SQL360：Python代码，命令行+Yaml配置文件。
