### ISSUE TITLE
关于论文中最优方案搜索中的变体方案构造的疑问。

### ISSUE THREAD

**Issue by wbbeyourself** [HKUSTDial/NL2SQL360#2]
请问论文中 NL2SQL360-AAS 中提到选出最优2个方案后，交换其某个模块后得到新的 A方案  ，然后对 A方案 再进行模块变体，得到 B方案。然后 B 方案再进入模型评测池。 请问为什么不把 A方案 也放入评测池呢？因为有可能 A方案 就是最优的模型啊。

![image](https://github.com/BugMaker-Boyan/NL2SQL360/assets/18190695/b1fe6237-a3d5-499e-95ac-31d939cc9f5f)

**Comment by BugMaker-Boyan** [comment]
感谢您对我们工作的关注。

NL2SQL360-AAS算法流程基于规范的GA算法，包括Individual Selection, Module Swap, Module Mutation三个操作算子，每一个新子代的产生都需要经过三个算子。然而，算子是概率发生的，我们在论文中有提到Module Swap Probability以及Module Mutation Probability。

具体地，您所提到的图中A和B两个方案，如果基于概率的突变此时没有发生，那么A方案将进入Population。

**Comment by wbbeyourself** [comment]
Nice，明白了，非常感谢。
